[rtla] Add compatibility for RHEL and Non-RHEL hosts and upstream RTLA
- The image can be built from RTLA upstream or from the repos
- Reduced image size to 170 - 300MB depending on config
- Made the Dockerfile compatible with non-RHEL hosts using centos:stream9.
- Added support for running with UBI9 for registered RHEL hosts.
- Introduced BASE_IMAGE build-arg to set the image type used.
- Incorporated RHEL_HOST to ensure user awareness of the IMAGE_BASE to use.
- Included checks for valid image names.
- Defaulted IMAGE_BASE to UBI9, but set RHEL_HOST to false, printing instructions
  to users when unconfigured.

Signed-off-by: Chris White <chwhite@redhat.com>

diff --git a/Dockerfile-rtla b/Dockerfile-rtla
--- a/Dockerfile-rtla
+++ b/Dockerfile-rtla
@@ -18,18 +18,58 @@
 # You should have received a copy of the GNU General Public License along with this program; 
 # if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 #
-FROM centos:stream9
-# In order for this to run on ubi8 or cs8, we need to package libtraceevent-devel libtracefs-devel in rhel8.
+ARG BASE_IMAGE=ubi9
+ARG RHEL_HOST=false
+ARG RTLA_UPSTREAM=false
+
+FROM ${BASE_IMAGE}
+
+ARG BASE_IMAGE
+ARG RHEL_HOST
+ARG RTLA_UPSTREAM
+RUN echo "Debug: BASE_IMAGE=${BASE_IMAGE}, RHEL_HOST=${RHEL_HOST}, RTLA_UPSTREAM=${RTLA_UPSTREAM}"
+
+# Use shell to check image_name conditions
+RUN if [[ ("$BASE_IMAGE" != "ubi9" && "$BASE_IMAGE" != "centos:stream9") ]]; then \
+    echo "ERROR: Invalid BASE_IMAGE given: ${BASE_IMAGE}."; \ 
+    echo "ERROR: The build-arg BASE_IMAGE must be either 'ubi9' for registered host or 'centos:stream9' for non-rhel host"; \
+    exit 1; \
+    fi
+
+# Use shell to check rhel host build conditions
+RUN if [[ "$RHEL_HOST" == "false" && "$BASE_IMAGE" == "ubi9" ]]; then \
+    echo "ERROR: You cannot use the ubi9 image on a non-RHEL host. If you have a RHEL host, set the '--build-arg RHEL_HOST=true'."; \
+    echo "ERROR: If you do not have a registered rhel host, set '--build-arg BASE_IMAGE=centos:stream9' instead."; \
+    exit 1; \
+    fi
+    
 # Set user to root
 USER root
-# Install required packages and dependencies for building/installing rtla. Right now this is configured for cs9
-RUN dnf -y update && dnf --enablerepo=crb -y install libtraceevent-devel libtracefs-devel python3-docutils git make gcc wget bzip2 && dnf clean all
-# Pull the most recent copy of rtla for linux tools. TODO: Make this pull from redhat repos
-RUN git clone https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git && \
-    cd linux/tools/tracing/rtla/ && \
-    make && \
-    make install && \
-    cd ../../../../ && rm -rf linux
+
+# Determine the correct repo to use based on the base image. Chain all steps together so
+# that the image size is smaller. If upstream enabled, build rtla from source. Otherwise,
+# simply pull from repos
+RUN if [[ "$RTLA_UPSTREAM" == "true" ]]; then \
+        base_image_check=$(cat /etc/redhat-release | awk '{print $1}'); \
+        if [ "$base_image_check" = "CentOS" ]; then \
+            enable_repo="crb"; \
+        else \
+            enable_repo="codeready-builder-for-rhel-9-$(arch)-rpms"; \
+        fi; \
+        dnf -y update && \
+        dnf --enablerepo=$enable_repo -y install \
+            libtraceevent-devel libtracefs-devel python3-docutils git make gcc wget bzip2 && \
+        git clone https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git && \
+        cd linux/tools/tracing/rtla/ && \
+        make && \
+        make install && \
+        cd ../../../../ && rm -rf linux; \
+        dnf remove -y libtraceevent-devel libtracefs-devel python3-docutils git make gcc wget bzip2; \ 
+    else \
+        dnf install rtla -y; \
+        echo "INFO: Pulling from repos. Please use '--build-arg RTLA_UPSTREAM=true' to build from upstream"; \   
+    fi; \
+    dnf clean all && rm -rf /var/cache/yum;
 
 # Install dumby init system
 RUN curl -L -o /root/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64 \
